### ISSUE TITLE
AttributeError occurring

### ISSUE THREAD

**Issue by BelloGoo** [eduanayardo/extract-color#1]
I tried to run your code exactly without modifications, but it comes up with this error: `AttributeError: 'NoneType' object has no attribute 'split'`.
Do you know anything about this? And how to fix this?
Thank you so much.

for this whole error message:
`Traceback (most recent call last):
  File "c:\Users\85270\OneDrive - 輔仁大學\桌面\Python\study\20240504.py", line 30, in <module>
    model = KMeans(n_clusters=n_colors, random_state=42).fit(pixels)
  File "C:\Users\85270\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py", line 1417, in fit
    labels, inertia, centers, n_iter_ = kmeans_single(
  File "C:\Users\85270\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py", line 646, in _kmeans_single_lloyd        
    with threadpool_limits(limits=1, user_api="blas"):
  File "C:\Users\85270\anaconda3\lib\site-packages\sklearn\utils\fixes.py", line 151, in threadpool_limits
    return threadpoolctl.threadpool_limits(limits=limits, user_api=user_api)
  File "C:\Users\85270\anaconda3\lib\site-packages\threadpoolctl.py", line 171, in __init__
    self._original_info = self._set_threadpool_limits()
  File "C:\Users\85270\anaconda3\lib\site-packages\threadpoolctl.py", line 268, in _set_threadpool_limits
    modules = _ThreadpoolInfo(prefixes=self._prefixes,
  File "C:\Users\85270\anaconda3\lib\site-packages\threadpoolctl.py", line 340, in __init__
    self._load_modules()
  File "C:\Users\85270\anaconda3\lib\site-packages\threadpoolctl.py", line 373, in _load_modules
    self._find_modules_with_enum_process_module_ex()
  File "C:\Users\85270\anaconda3\lib\site-packages\threadpoolctl.py", line 485, in _find_modules_with_enum_process_module_ex
    self._make_module_from_path(filepath)
  File "C:\Users\85270\anaconda3\lib\site-packages\threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
  File "C:\Users\85270\anaconda3\lib\site-packages\threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
  File "C:\Users\85270\anaconda3\lib\site-packages\threadpoolctl.py", line 646, in get_version
    config = get_config().split()
AttributeError: 'NoneType' object has no attribute 'split'`

**Comment by BelloGoo** [comment]
i found the way.
`pip install threadpoolctl==3.1.0`
just upgrade the threadpoolctl would fix the problem.
thanks for your help.
